# Importations of Modules

In [34]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Part 1: Inspecting the Data

Loading the dataset

In [35]:
df = pd.read_csv("loan_customers.csv")
df

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,24,120000,500000,620.0,2,0,35000,18000,7,120000,Male,Private,Akwa Ibom,No,No
1,C002,45,450000,1200000,780.0,18,3,450000,25000,9,450000,Female,Government,Lagos,Yes,No
2,C003,31,210000,800000,690.0,6,1,120000,20000,8,210000,Male,Private,Rivers,No,No
3,C004,52,600000,1500000,810.0,25,4,800000,30000,9,600000,Female,Government,Abuja,Yes,No
4,C005,27,95000,450000,590.0,1,0,15000,16000,5,95000,Male,Self-employed,Akwa Ibom,No,Yes
5,C006,39,320000,900000,NaN,12,2,280000,22000,8,320000,Female,Private,Lagos,Yes,No
6,C007,29,150000,600000,640.0,4,1,50000,19000,6,150000,Male,Private,Rivers,NaN,Yes
7,C008,48,520000,1300000,790.0,21,3,600000,28000,10,520000,Female,Government,Lagos,Yes,No
8,C009,34,250000,850000,700.0,8,2,180000,21000,7,250000,Male,Private,Akwa Ibom,No,No
9,C010,41,380000,1000000,750.0,15,2,350000,24000,8,380000,Female,Self-employed,Rivers,Yes,No
10,C011,23,85000,400000,580.0,1,0,10000,15000,4,85000,Female,Private,Akwa Ibom,No,Yes
11,C012,56,700000,1600000,820.0,30,5,950000,32000,10,700000,Male,Government,Abuja,Yes,No
12,C013,37,280000,750000,NaN,10,2,220000,21000,7,280000,Male,Private,Lagos,NaN,No
13,C014,30,’ ’,550000,NaN,5,1,70000,18000,6,’ ’,Female,Private,Rivers,No,Yes
14,C015,43,410000,1100000,760.0,16,3,400000,25000,9,410000,Female,Government,Lagos,Yes,No
15,C016,26,110000,480000,600.0,2,0,20000,17000,5,110000,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,35,260000,850000,705.0,9,2,160000,21000,7,260000,Female,Private,Rivers,Yes,No
17,C018,49,15000000,50000000,800.0,23,4,9000000,35000,10,15000000,Male,Government,Abuja,Yes,No
18,C019,28,130000,520000,630.0,3,1,40000,18000,6,130000,Female,Private,Akwa Ibom,No,Yes
19,C020,40,350000,950000,740.0,14,2,310000,23000,8,350000,Male,Self-employed,Lagos,Yes,No

Display the first 5 rows

In [36]:
df.head()

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,24,120000,500000,620.0,2,0,35000,18000,7,120000,Male,Private,Akwa Ibom,No,No
1,C002,45,450000,1200000,780.0,18,3,450000,25000,9,450000,Female,Government,Lagos,Yes,No
2,C003,31,210000,800000,690.0,6,1,120000,20000,8,210000,Male,Private,Rivers,No,No
3,C004,52,600000,1500000,810.0,25,4,800000,30000,9,600000,Female,Government,Abuja,Yes,No
4,C005,27,95000,450000,590.0,1,0,15000,16000,5,95000,Male,Self-employed,Akwa Ibom,No,Yes

Display the last 5 rows

In [37]:
df.tail()

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
15,C016,26,110000,480000,600.0,2,0,20000,17000,5,110000,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,35,260000,850000,705.0,9,2,160000,21000,7,260000,Female,Private,Rivers,Yes,No
17,C018,49,15000000,50000000,800.0,23,4,9000000,35000,10,15000000,Male,Government,Abuja,Yes,No
18,C019,28,130000,520000,630.0,3,1,40000,18000,6,130000,Female,Private,Akwa Ibom,No,Yes
19,C020,40,350000,950000,740.0,14,2,310000,23000,8,350000,Male,Self-employed,Lagos,Yes,No

Shape of the dataset

In [38]:
Row, Column = df.shape
print(f"Row: {Row}")
print(f"Column: {Column}")

Row: 20
Column: 16

Column names in the dataset

In [39]:
df.columns

Index(['Customer_ID', 'Age', 'Monthly_Income', 'Loan_Amount', 'Credit_Score',
       'Years_Employed', 'Num_Children', 'Savings_Balance',
       'Monthly_Transport', 'Satisfaction_Score', 'Income_Copy', 'Gender',
       'Employment_Type', 'State', 'Owns_House', 'Defaulted'],
      dtype='str')

Datatypes of all columns

In [40]:
df.dtypes

Customer_ID               str
Age                     int64
Monthly_Income            str
Loan_Amount             int64
Credit_Score          float64
Years_Employed          int64
Num_Children            int64
Savings_Balance         int64
Monthly_Transport       int64
Satisfaction_Score      int64
Income_Copy               str
Gender                    str
Employment_Type           str
State                     str
Owns_House                str
Defaulted                 str
dtype: object

Summary of the dataset

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         20 non-null     str
 1   Age                 20 non-null     int64
 2   Monthly_Income      20 non-null     str
 3   Loan_Amount         20 non-null     int64
 4   Credit_Score        17 non-null     float64
 5   Years_Employed      20 non-null     int64
 6   Num_Children        20 non-null     int64
 7   Savings_Balance     20 non-null     int64
 8   Monthly_Transport   20 non-null     int64
 9   Satisfaction_Score  20 non-null     int64
 10  Income_Copy         20 non-null     str
 11  Gender              20 non-null     str
 12  Employment_Type     20 non-null     str
 13  State               20 non-null     str
 14  Owns_House          18 non-null     str
 15  Defaulted           20 non-null     str
dtypes: float64(1), int64(7), str(8)
memory usage: 2.6 KB

Statistical Summary of the dataset

In [42]:
df.describe()

,Age,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score
count,20.000000,2.000000e+01,17.000000,20.000000,20.000000,2.000000e+01,20.000000,20.000000
mean,36.850000,3.315000e+06,706.176471,11.250000,1.900000,7.030000e+05,22400.000000,7.450000
std,9.756374,1.099402e+07,82.755842,8.735138,1.447321,1.970968e+06,5442.522635,1.761429
min,23.000000,4.000000e+05,580.000000,1.000000,0.000000,1.000000e+04,15000.000000,4.000000
25%,28.750000,5.425000e+05,630.000000,3.750000,1.000000,4.750000e+04,18000.000000,6.000000
50%,36.000000,8.500000e+05,705.000000,9.500000,2.000000,2.000000e+05,21000.000000,7.500000
75%,43.500000,1.125000e+06,780.000000,16.500000,3.000000,4.125000e+05,25000.000000,9.000000
max,56.000000,5.000000e+07,820.000000,30.000000,5.000000,9.000000e+06,35000.000000,10.000000

Numerical Columns

In [43]:
df.select_dtypes(include=['number']).columns

Index(['Age', 'Loan_Amount', 'Credit_Score', 'Years_Employed', 'Num_Children',
       'Savings_Balance', 'Monthly_Transport', 'Satisfaction_Score'],
      dtype='str')

Categorical Columns

In [44]:
df.select_dtypes(include=['string']).columns

Index(['Customer_ID', 'Monthly_Income', 'Income_Copy', 'Gender',
       'Employment_Type', 'State', 'Owns_House', 'Defaulted'],
      dtype='str')

Identifying Target Variable

The Target Variable is "Defaulted" because we're trying to predict which customers have not paid off their loans

Column Identifiers

These are columns with no repetition of feature in them...

In [45]:
Identifier_Columns = [col for col in df.columns if df[col].nunique() == len(df)]
Identifier_Columns

['Customer_ID', 'Age', 'Monthly_Income', 'Savings_Balance', 'Income_Copy']

# Question

Are all columns correctly represented by their current data types?

If not, identify the problematic column(s) and explain why.

# Answer

No... 

The Monthly_Income and the Income_Copy columns are the problematic columns... 

Because "dtypes" function identify them as strings whereas they're supposed to be integers...

# Part 2: Missing Values

Checking if the dataset has missing values

In [46]:
df.isnull().sum()

Customer_ID           0
Age                   0
Monthly_Income        0
Loan_Amount           0
Credit_Score          3
Years_Employed        0
Num_Children          0
Savings_Balance       0
Monthly_Transport     0
Satisfaction_Score    0
Income_Copy           0
Gender                0
Employment_Type       0
State                 0
Owns_House            2
Defaulted             0
dtype: int64

Columns with missing values

In [47]:
df.Credit_Score.isna().sum()

np.int64(3)

In [48]:
df.Owns_House.isna().sum()

np.int64(2)

Determining what represents a missing values

In [49]:
print("\nUnique value frequencies:")
print(df.value_counts(dropna=False))

Unique value frequencies:
Customer_ID  Age  Monthly_Income  Loan_Amount  Credit_Score  Years_Employed  Num_Children  Savings_Balance  Monthly_Transport  Satisfaction_Score  Income_Copy  Gender  Employment_Type  State      Owns_House  Defaulted
C001         24   120000          500000       620.0         2               0             35000            18000              7                   120000       Male    Private          Akwa Ibom  No          No           1
C002         45   450000          1200000      780.0         18              3             450000           25000              9                   450000       Female  Government       Lagos      Yes         No           1
C003         31   210000          800000       690.0         6               1             120000           20000              8                   210000       Male    Private          Rivers     No          No           1
C004         52   600000          1500000      810.0         25              4             800000           30000              9                   600000       Female  Government       Abuja      Yes         No           1
C005         27   95000           450000       590.0         1               0             15000            16000              5                   95000        Male    Self-employed    Akwa Ibom  No          Yes          1
C006         39   320000          900000       NaN           12              2             280000           22000              8                   320000       Female  Private          Lagos      Yes         No           1
C007         29   150000          600000       640.0         4               1             50000            19000              6                   150000       Male    Private          Rivers     NaN         Yes          1
C008         48   520000          1300000      790.0         21              3             600000           28000              10                  520000       Female  Government       Lagos      Yes         No           1
C009         34   250000          850000       700.0         8               2             180000           21000              7                   250000       Male    Private          Akwa Ibom  No          No           1
C010         41   380000          1000000      750.0         15              2             350000           24000              8                   380000       Female  Self-employed    Rivers     Yes         No           1
C011         23   85000           400000       580.0         1               0             10000            15000              4                   85000        Female  Private          Akwa Ibom  No          Yes          1
C012         56   700000          1600000      820.0         30              5             950000           32000              10                  700000       Male    Government       Abuja      Yes         No           1
C013         37   280000          750000       NaN           10              2             220000           21000              7                   280000       Male    Private          Lagos      NaN         No           1
C014         30   ’ ’             550000       NaN           5               1             70000            18000              6                   ’ ’          Female  Private          Rivers     No          Yes          1
C015         43   410000          1100000      760.0         16              3             400000           25000              9                   410000       Female  Government       Lagos      Yes         No           1
C016         26   110000          480000       600.0         2               0             20000            17000              5                   110000       Male    Self-employed    Akwa Ibom  No          Yes          1
C017         35   260000          850000       705.0         9               2             160000           21000              7                   260000       Female  Private          Rivers     Yes         No           1
C018         49   15000000        50000000     800.0         23              4             9000000          35000              10                  15000000     Male    Government       Abuja      Yes         No           1
C019         28   130000          520000       630.0         3               1             40000            18000              6                   130000       Female  Private          Akwa Ibom  No          Yes          1
C020         40   350000          950000       740.0         14              2             310000           23000              8                   350000       Male    Self-employed    Lagos      Yes         No           1
Name: count, dtype: int64

The missing values are represented by " ' ' " and "NaN"

Simply using "df.isna().sum()" may not be sufficient in detecting all the types of mssing data because traditionally, pandas can only check for Mock Values like NAN, NULL, NONE e.t.c and just like seen in the dataset above miss empty spaces due to human error

Converting ' ' missing values in Monthly_Income and Income_Copy into an appropriate representation which is NaN

In [50]:
df["Monthly_Income"] = pd.to_numeric(df["Monthly_Income"], errors="coerce")
df.Monthly_Income

0       120000.0
1       450000.0
2       210000.0
3       600000.0
4        95000.0
5       320000.0
6       150000.0
7       520000.0
8       250000.0
9       380000.0
10       85000.0
11      700000.0
12      280000.0
13           NaN
14      410000.0
15      110000.0
16      260000.0
17    15000000.0
18      130000.0
19      350000.0
Name: Monthly_Income, dtype: float64

In [51]:
df["Income_Copy"] = pd.to_numeric(df["Income_Copy"], errors="coerce")
df.Income_Copy

0       120000.0
1       450000.0
2       210000.0
3       600000.0
4        95000.0
5       320000.0
6       150000.0
7       520000.0
8       250000.0
9       380000.0
10       85000.0
11      700000.0
12      280000.0
13           NaN
14      410000.0
15      110000.0
16      260000.0
17    15000000.0
18      130000.0
19      350000.0
Name: Income_Copy, dtype: float64

In [52]:
df

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,24,120000.0,500000,620.0,2,0,35000,18000,7,120000.0,Male,Private,Akwa Ibom,No,No
1,C002,45,450000.0,1200000,780.0,18,3,450000,25000,9,450000.0,Female,Government,Lagos,Yes,No
2,C003,31,210000.0,800000,690.0,6,1,120000,20000,8,210000.0,Male,Private,Rivers,No,No
3,C004,52,600000.0,1500000,810.0,25,4,800000,30000,9,600000.0,Female,Government,Abuja,Yes,No
4,C005,27,95000.0,450000,590.0,1,0,15000,16000,5,95000.0,Male,Self-employed,Akwa Ibom,No,Yes
5,C006,39,320000.0,900000,NaN,12,2,280000,22000,8,320000.0,Female,Private,Lagos,Yes,No
6,C007,29,150000.0,600000,640.0,4,1,50000,19000,6,150000.0,Male,Private,Rivers,NaN,Yes
7,C008,48,520000.0,1300000,790.0,21,3,600000,28000,10,520000.0,Female,Government,Lagos,Yes,No
8,C009,34,250000.0,850000,700.0,8,2,180000,21000,7,250000.0,Male,Private,Akwa Ibom,No,No
9,C010,41,380000.0,1000000,750.0,15,2,350000,24000,8,380000.0,Female,Self-employed,Rivers,Yes,No
10,C011,23,85000.0,400000,580.0,1,0,10000,15000,4,85000.0,Female,Private,Akwa Ibom,No,Yes
11,C012,56,700000.0,1600000,820.0,30,5,950000,32000,10,700000.0,Male,Government,Abuja,Yes,No
12,C013,37,280000.0,750000,NaN,10,2,220000,21000,7,280000.0,Male,Private,Lagos,NaN,No
13,C014,30,NaN,550000,NaN,5,1,70000,18000,6,NaN,Female,Private,Rivers,No,Yes
14,C015,43,410000.0,1100000,760.0,16,3,400000,25000,9,410000.0,Female,Government,Lagos,Yes,No
15,C016,26,110000.0,480000,600.0,2,0,20000,17000,5,110000.0,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,35,260000.0,850000,705.0,9,2,160000,21000,7,260000.0,Female,Private,Rivers,Yes,No
17,C018,49,15000000.0,50000000,800.0,23,4,9000000,35000,10,15000000.0,Male,Government,Abuja,Yes,No
18,C019,28,130000.0,520000,630.0,3,1,40000,18000,6,130000.0,Female,Private,Akwa Ibom,No,Yes
19,C020,40,350000.0,950000,740.0,14,2,310000,23000,8,350000.0,Male,Self-employed,Lagos,Yes,No

The missing values should be handled by filling them... 

Now I determined that I can fill Monthly_Income and Income_Copy with median because income is usually highly skewed and I don't want outliers affecting the column by using mean and mode, so it's best I use median that just picks inbetween... 

I also decide to fill Credit_Score with median because I'm trying to prevent outliers... 

I decide to fill Owns_House with mode because it's a Boolean column and the best approach to Boolean columns is mode...

In [53]:
# Filling Monthly_Income with median
df['Monthly_Income'] = df['Monthly_Income'].fillna(df['Monthly_Income'].median())

# Filling Income_Copy with median
df['Income_Copy'] = df['Income_Copy'].fillna(df['Income_Copy'].median())

# Filling Credit_Score with median
df['Credit_Score'] = df['Credit_Score'].fillna(df['Credit_Score'].median())

# Filling Own_House with mode
df['Owns_House'] = df['Owns_House'].fillna(df['Owns_House'].mode()[0])

In [54]:
df.Monthly_Income

0       120000.0
1       450000.0
2       210000.0
3       600000.0
4        95000.0
5       320000.0
6       150000.0
7       520000.0
8       250000.0
9       380000.0
10       85000.0
11      700000.0
12      280000.0
13      280000.0
14      410000.0
15      110000.0
16      260000.0
17    15000000.0
18      130000.0
19      350000.0
Name: Monthly_Income, dtype: float64

In [55]:
df.Income_Copy

0       120000.0
1       450000.0
2       210000.0
3       600000.0
4        95000.0
5       320000.0
6       150000.0
7       520000.0
8       250000.0
9       380000.0
10       85000.0
11      700000.0
12      280000.0
13      280000.0
14      410000.0
15      110000.0
16      260000.0
17    15000000.0
18      130000.0
19      350000.0
Name: Income_Copy, dtype: float64

In [56]:
df.Credit_Score

0     620.0
1     780.0
2     690.0
3     810.0
4     590.0
5     705.0
6     640.0
7     790.0
8     700.0
9     750.0
10    580.0
11    820.0
12    705.0
13    705.0
14    760.0
15    600.0
16    705.0
17    800.0
18    630.0
19    740.0
Name: Credit_Score, dtype: float64

In [57]:
df.Owns_House

0      No
1     Yes
2      No
3     Yes
4      No
5     Yes
6     Yes
7     Yes
8      No
9     Yes
10     No
11    Yes
12    Yes
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
Name: Owns_House, dtype: str

In [58]:
df.isna().sum()

Customer_ID           0
Age                   0
Monthly_Income        0
Loan_Amount           0
Credit_Score          0
Years_Employed        0
Num_Children          0
Savings_Balance       0
Monthly_Transport     0
Satisfaction_Score    0
Income_Copy           0
Gender                0
Employment_Type       0
State                 0
Owns_House            0
Defaulted             0
dtype: int64

# Part 3: Duplicate Features

Yes, two columns contain duplicates...

The duplicated columns are Monthly_Income and Income_Copy

Keeping duplicate features in a dataset or machine learning model can cause major issues that hurt performance and efficiency through redundant data or variables

The Monthly_Income column should be retained because the Income_Copy column is essentially a copy of the Monthly_Income column

In [59]:
df.drop(columns = "Income_Copy")

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,24,120000.0,500000,620.0,2,0,35000,18000,7,Male,Private,Akwa Ibom,No,No
1,C002,45,450000.0,1200000,780.0,18,3,450000,25000,9,Female,Government,Lagos,Yes,No
2,C003,31,210000.0,800000,690.0,6,1,120000,20000,8,Male,Private,Rivers,No,No
3,C004,52,600000.0,1500000,810.0,25,4,800000,30000,9,Female,Government,Abuja,Yes,No
4,C005,27,95000.0,450000,590.0,1,0,15000,16000,5,Male,Self-employed,Akwa Ibom,No,Yes
5,C006,39,320000.0,900000,705.0,12,2,280000,22000,8,Female,Private,Lagos,Yes,No
6,C007,29,150000.0,600000,640.0,4,1,50000,19000,6,Male,Private,Rivers,Yes,Yes
7,C008,48,520000.0,1300000,790.0,21,3,600000,28000,10,Female,Government,Lagos,Yes,No
8,C009,34,250000.0,850000,700.0,8,2,180000,21000,7,Male,Private,Akwa Ibom,No,No
9,C010,41,380000.0,1000000,750.0,15,2,350000,24000,8,Female,Self-employed,Rivers,Yes,No
10,C011,23,85000.0,400000,580.0,1,0,10000,15000,4,Female,Private,Akwa Ibom,No,Yes
11,C012,56,700000.0,1600000,820.0,30,5,950000,32000,10,Male,Government,Abuja,Yes,No
12,C013,37,280000.0,750000,705.0,10,2,220000,21000,7,Male,Private,Lagos,Yes,No
13,C014,30,280000.0,550000,705.0,5,1,70000,18000,6,Female,Private,Rivers,No,Yes
14,C015,43,410000.0,1100000,760.0,16,3,400000,25000,9,Female,Government,Lagos,Yes,No
15,C016,26,110000.0,480000,600.0,2,0,20000,17000,5,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,35,260000.0,850000,705.0,9,2,160000,21000,7,Female,Private,Rivers,Yes,No
17,C018,49,15000000.0,50000000,800.0,23,4,9000000,35000,10,Male,Government,Abuja,Yes,No
18,C019,28,130000.0,520000,630.0,3,1,40000,18000,6,Female,Private,Akwa Ibom,No,Yes
19,C020,40,350000.0,950000,740.0,14,2,310000,23000,8,Male,Self-employed,Lagos,Yes,No

# Question... 

Why is this different from Pearson correlation? 

# Answer... 

The column dropped(Income_Copy) is a direct identical repeat copy of another column(Monthly_Income) while Pearson Correlation is used to measure a broader range of lineear relationships between two columns

In [60]:
df.duplicated().sum()

np.int64(0)

# Part 4: Variance Analysis

In [61]:
Variances = df.var(numeric_only=True)
Variances

Age                   9.518684e+01
Monthly_Income        1.083416e+13
Loan_Amount           1.208685e+14
Credit_Score          5.767368e+03
Years_Employed        7.630263e+01
Num_Children          2.094737e+00
Savings_Balance       3.884714e+12
Monthly_Transport     2.962105e+07
Satisfaction_Score    3.102632e+00
Income_Copy           1.083416e+13
dtype: float64

In [62]:
numerical_columns = [
    'Age', 'Monthly_Income', 'Loan_Amount', 'Credit_Score', 'Years_Employed',
    'Num_Children', 'Savings_Balance', 'Monthly_Transport', 'Satisfaction_Score'
]
numeric_columns = df[numerical_columns].copy()
numeric_columns

,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score
0,24,120000.0,500000,620.0,2,0,35000,18000,7
1,45,450000.0,1200000,780.0,18,3,450000,25000,9
2,31,210000.0,800000,690.0,6,1,120000,20000,8
3,52,600000.0,1500000,810.0,25,4,800000,30000,9
4,27,95000.0,450000,590.0,1,0,15000,16000,5
5,39,320000.0,900000,705.0,12,2,280000,22000,8
6,29,150000.0,600000,640.0,4,1,50000,19000,6
7,48,520000.0,1300000,790.0,21,3,600000,28000,10
8,34,250000.0,850000,700.0,8,2,180000,21000,7
9,41,380000.0,1000000,750.0,15,2,350000,24000,8
10,23,85000.0,400000,580.0,1,0,10000,15000,4
11,56,700000.0,1600000,820.0,30,5,950000,32000,10
12,37,280000.0,750000,705.0,10,2,220000,21000,7
13,30,280000.0,550000,705.0,5,1,70000,18000,6
14,43,410000.0,1100000,760.0,16,3,400000,25000,9
15,26,110000.0,480000,600.0,2,0,20000,17000,5
16,35,260000.0,850000,705.0,9,2,160000,21000,7
17,49,15000000.0,50000000,800.0,23,4,9000000,35000,10
18,28,130000.0,520000,630.0,3,1,40000,18000,6
19,40,350000.0,950000,740.0,14,2,310000,23000,8

Low Variance means that datapoints in a specific column are highly similar to eacch other and do not deviate much from the columns' average mean value

A feature with no variation provides little to no useful information because Machines learn from differences, contrasts and pattern in data

In [63]:
Variance_Instance = VarianceThreshold(threshold=0.5)
data_var = Variance_Instance.fit_transform(numeric_columns)
selected_columns = numeric_columns.columns[Variance_Instance.get_support()]
filtered_df = numeric_columns.loc[:, selected_columns].copy()
filtered_df

,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score
0,24,120000.0,500000,620.0,2,0,35000,18000,7
1,45,450000.0,1200000,780.0,18,3,450000,25000,9
2,31,210000.0,800000,690.0,6,1,120000,20000,8
3,52,600000.0,1500000,810.0,25,4,800000,30000,9
4,27,95000.0,450000,590.0,1,0,15000,16000,5
5,39,320000.0,900000,705.0,12,2,280000,22000,8
6,29,150000.0,600000,640.0,4,1,50000,19000,6
7,48,520000.0,1300000,790.0,21,3,600000,28000,10
8,34,250000.0,850000,700.0,8,2,180000,21000,7
9,41,380000.0,1000000,750.0,15,2,350000,24000,8
10,23,85000.0,400000,580.0,1,0,10000,15000,4
11,56,700000.0,1600000,820.0,30,5,950000,32000,10
12,37,280000.0,750000,705.0,10,2,220000,21000,7
13,30,280000.0,550000,705.0,5,1,70000,18000,6
14,43,410000.0,1100000,760.0,16,3,400000,25000,9
15,26,110000.0,480000,600.0,2,0,20000,17000,5
16,35,260000.0,850000,705.0,9,2,160000,21000,7
17,49,15000000.0,50000000,800.0,23,4,9000000,35000,10
18,28,130000.0,520000,630.0,3,1,40000,18000,6
19,40,350000.0,950000,740.0,14,2,310000,23000,8

In [64]:
for col, var in zip(filtered_df.columns, Variance_Instance.variances_):
    print(f"{col}: {var}")

Age: 90.42749999999998
Monthly_Income: 10292447500000.0
Loan_Amount: 114825065000000.0
Credit_Score: 5479.0
Years_Employed: 72.4875
Num_Children: 1.9900000000000002
Savings_Balance: 3690478500000.0
Monthly_Transport: 28140000.0
Satisfaction_Score: 2.9475000000000002

# Question...

Why should you not blindly use the default threshold?

Should the target variable be included in this analysis?

Should Customer_ID be included?

Should categorical columns be passed directly into VarianceThreshold?

# Answers...

The default threshold only catches features with zero variance. It fails to remove noise.

No, becasue it could lead to data leakages.

No, because it is a string and also an Identifier.

No, they shouldn't be passed into VarianceThreshold until they are OneHotEncoded or Mapped in Numerics

# Part 5: Feature Scaling

# 5.1 

Scaler Necessity: Features like "Monthly_Income" reach into millions, while "Age" values hover under 60. Left unscaled, distance-based models assume income is vastly more important than age simply due to its unit magnitude.

What StandardScaler does: It centers the column distribution around \(0\) with unit variance.

Mean destination: It shifts exactly to 0.

Standard Deviation destination: It scales exactly to 1.

Features to standardize: Age, Credit_Score, Years_Employed, Num_Children, Monthly_Transport, Satisfaction_Score. These are the features without extreme skew or massive outliers.

In [65]:
Scaler = StandardScaler()

#Age StandardScaler
Scaler.set_output(transform="pandas")
StandardAge = Scaler.fit_transform(df[['Age']])
df['Age'] = StandardAge

#Credit_Score StandardScaler
Scaler.set_output(transform="pandas")
StandardCredit_Score = Scaler.fit_transform(df[['Credit_Score']])
df['Credit_Score'] = StandardCredit_Score

#Years_Employed StandardScaler
Scaler.set_output(transform="pandas")
StandardYears_Employed = Scaler.fit_transform(df[['Years_Employed']])
df['Years_Employed'] = StandardYears_Employed

#Num_Children StandardScaler
Scaler.set_output(transform="pandas")
StandardNum_Children = Scaler.fit_transform(df[['Num_Children']])
df['Num_Children'] = StandardNum_Children

#Monthly_Transport StandardScaler
Scaler.set_output(transform="pandas")
StandardMonthly_Transport = Scaler.fit_transform(df[['Monthly_Transport']])
df['Monthly_Transport'] = StandardMonthly_Transport

#Satisfaction_Score StandardScaler
Scaler.set_output(transform="pandas")
StandardSatisfaction_Score = Scaler.fit_transform(df[['Satisfaction_Score']])
df['Satisfaction_Score'] = StandardSatisfaction_Score

df

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,-1.351303,120000.0,500000,-1.161844,-1.086451,-1.346874,35000,-0.829451,-0.262111,120000.0,Male,Private,Akwa Ibom,No,No
1,C002,0.857052,450000.0,1200000,0.999726,0.792816,0.779769,450000,0.490130,0.902828,450000.0,Female,Government,Lagos,Yes,No
2,C003,-0.615185,210000.0,800000,-0.216157,-0.616634,-0.637993,120000,-0.452428,0.320358,210000.0,Male,Private,Rivers,No,No
3,C004,1.593171,600000.0,1500000,1.405021,1.614995,1.488651,800000,1.432688,0.902828,600000.0,Female,Government,Abuja,Yes,No
4,C005,-1.035824,95000.0,450000,-1.567138,-1.203905,-1.346874,15000,-1.206474,-1.427050,95000.0,Male,Self-employed,Akwa Ibom,No,Yes
5,C006,0.226094,320000.0,900000,-0.013510,0.088091,0.070888,280000,-0.075405,0.320358,320000.0,Female,Private,Lagos,Yes,No
6,C007,-0.825504,150000.0,600000,-0.891648,-0.851543,-0.637993,50000,-0.640939,-0.844581,150000.0,Male,Private,Rivers,Yes,Yes
7,C008,1.172532,520000.0,1300000,1.134824,1.145178,0.779769,600000,1.055665,1.485297,520000.0,Female,Government,Lagos,Yes,No
8,C009,-0.299705,250000.0,850000,-0.081059,-0.381726,0.070888,180000,-0.263916,-0.262111,250000.0,Male,Private,Akwa Ibom,No,No
9,C010,0.436413,380000.0,1000000,0.594432,0.440453,0.070888,350000,0.301618,0.320358,380000.0,Female,Self-employed,Rivers,Yes,No
10,C011,-1.456463,85000.0,400000,-1.702236,-1.203905,-1.346874,10000,-1.394985,-2.009519,85000.0,Female,Private,Akwa Ibom,No,Yes
11,C012,2.013810,700000.0,1600000,1.540119,2.202266,2.197532,950000,1.809711,1.485297,700000.0,Male,Government,Abuja,Yes,No
12,C013,0.015774,280000.0,750000,-0.013510,-0.146818,0.070888,220000,-0.263916,-0.262111,280000.0,Male,Private,Lagos,Yes,No
13,C014,-0.720345,280000.0,550000,-0.013510,-0.734089,-0.637993,70000,-0.829451,-0.844581,280000.0,Female,Private,Rivers,No,Yes
14,C015,0.646733,410000.0,1100000,0.729530,0.557907,0.779769,400000,0.490130,0.902828,410000.0,Female,Government,Lagos,Yes,No
15,C016,-1.140984,110000.0,480000,-1.432040,-1.086451,-1.346874,20000,-1.017962,-1.427050,110000.0,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,-0.194546,260000.0,850000,-0.013510,-0.264272,0.070888,160000,-0.263916,-0.262111,260000.0,Female,Private,Rivers,Yes,No
17,C018,1.277692,15000000.0,50000000,1.269922,1.380086,1.488651,9000000,2.375245,1.485297,15000000.0,Male,Government,Abuja,Yes,No
18,C019,-0.930664,130000.0,520000,-1.026746,-0.968997,-0.637993,40000,-0.829451,-0.844581,130000.0,Female,Private,Akwa Ibom,No,Yes
19,C020,0.331253,350000.0,950000,0.459334,0.322999,0.070888,310000,0.113107,0.320358,350000.0,Male,Self-employed,Lagos,Yes,No

# 5.2

MinMaxScalerRange: Transforms data precisely into a [0, 1] bound.

Usefulness: Excellent for algorithms that require defined lower and upper bounds, such as neural networks or image processing setups.

Extreme value impact: Outliers compress all normal records into a tiny, indistinguishable band close to zero.

Affected Features: Monthly_Income, Loan_Amount, and Savings_Balance are heavily compressed due to the massive outlier present in customer record C018

In [66]:
Scaler = MinMaxScaler()

# Monthly_Income MinMaxScaler
Scaler.set_output(transform="pandas")
MinMaxMonthly_Income = Scaler.fit_transform(df[['Monthly_Income']])
df['Monthly_Income'] = MinMaxMonthly_Income

# Loan_Amount MinMaxScaler
Scaler.set_output(transform="pandas")
MinMaxLoan_Amount = Scaler.fit_transform(df[['Loan_Amount']])
df['Loan_Amount'] = MinMaxLoan_Amount

# Savings_Balance MinMaxScaler
Scaler.set_output(transform="pandas")
MinMaxSavings_Balance = Scaler.fit_transform(df[['Savings_Balance']])
df['Savings_Balance'] = MinMaxSavings_Balance

df

,Customer_ID,Age,Monthly_Income,Loan_Amount,Credit_Score,Years_Employed,Num_Children,Savings_Balance,Monthly_Transport,Satisfaction_Score,Income_Copy,Gender,Employment_Type,State,Owns_House,Defaulted
0,C001,-1.351303,0.002347,0.002016,-1.161844,-1.086451,-1.346874,0.002781,-0.829451,-0.262111,120000.0,Male,Private,Akwa Ibom,No,No
1,C002,0.857052,0.024472,0.016129,0.999726,0.792816,0.779769,0.048943,0.490130,0.902828,450000.0,Female,Government,Lagos,Yes,No
2,C003,-0.615185,0.008381,0.008065,-0.216157,-0.616634,-0.637993,0.012236,-0.452428,0.320358,210000.0,Male,Private,Rivers,No,No
3,C004,1.593171,0.034529,0.022177,1.405021,1.614995,1.488651,0.087875,1.432688,0.902828,600000.0,Female,Government,Abuja,Yes,No
4,C005,-1.035824,0.000670,0.001008,-1.567138,-1.203905,-1.346874,0.000556,-1.206474,-1.427050,95000.0,Male,Self-employed,Akwa Ibom,No,Yes
5,C006,0.226094,0.015756,0.010081,-0.013510,0.088091,0.070888,0.030033,-0.075405,0.320358,320000.0,Female,Private,Lagos,Yes,No
6,C007,-0.825504,0.004358,0.004032,-0.891648,-0.851543,-0.637993,0.004449,-0.640939,-0.844581,150000.0,Male,Private,Rivers,Yes,Yes
7,C008,1.172532,0.029165,0.018145,1.134824,1.145178,0.779769,0.065628,1.055665,1.485297,520000.0,Female,Government,Lagos,Yes,No
8,C009,-0.299705,0.011063,0.009073,-0.081059,-0.381726,0.070888,0.018910,-0.263916,-0.262111,250000.0,Male,Private,Akwa Ibom,No,No
9,C010,0.436413,0.019779,0.012097,0.594432,0.440453,0.070888,0.037820,0.301618,0.320358,380000.0,Female,Self-employed,Rivers,Yes,No
10,C011,-1.456463,0.000000,0.000000,-1.702236,-1.203905,-1.346874,0.000000,-1.394985,-2.009519,85000.0,Female,Private,Akwa Ibom,No,Yes
11,C012,2.013810,0.041234,0.024194,1.540119,2.202266,2.197532,0.104561,1.809711,1.485297,700000.0,Male,Government,Abuja,Yes,No
12,C013,0.015774,0.013074,0.007056,-0.013510,-0.146818,0.070888,0.023359,-0.263916,-0.262111,280000.0,Male,Private,Lagos,Yes,No
13,C014,-0.720345,0.013074,0.003024,-0.013510,-0.734089,-0.637993,0.006674,-0.829451,-0.844581,280000.0,Female,Private,Rivers,No,Yes
14,C015,0.646733,0.021790,0.014113,0.729530,0.557907,0.779769,0.043382,0.490130,0.902828,410000.0,Female,Government,Lagos,Yes,No
15,C016,-1.140984,0.001676,0.001613,-1.432040,-1.086451,-1.346874,0.001112,-1.017962,-1.427050,110000.0,Male,Self-employed,Akwa Ibom,No,Yes
16,C017,-0.194546,0.011733,0.009073,-0.013510,-0.264272,0.070888,0.016685,-0.263916,-0.262111,260000.0,Female,Private,Rivers,Yes,No
17,C018,1.277692,1.000000,1.000000,1.269922,1.380086,1.488651,1.000000,2.375245,1.485297,15000000.0,Male,Government,Abuja,Yes,No
18,C019,-0.930664,0.003017,0.002419,-1.026746,-0.968997,-0.637993,0.003337,-0.829451,-0.844581,130000.0,Female,Private,Akwa Ibom,No,Yes
19,C020,0.331253,0.017767,0.011089,0.459334,0.322999,0.070888,0.033370,0.113107,0.320358,350000.0,Male,Self-employed,Lagos,Yes,No

# 5.3

Difference: It uses the Median and Interquartile Range (IQR) for scaling instead of the Mean and Standard Deviation as StandardScaler does.

Outlier Utility: Because the median and IQR ignore extreme trailing tails, outliers do not warp the scaling of regular customer records.

Extreme Value Columns: Monthly_Income, Loan_Amount, and Savings_Balance.

Most Appropriate Scaler: RobustScaler is the most optimal choice for these specific heavily skewed features.

Universal application rule: No, RobustScaler should not be used universally. For features with standard normal distributions, StandardScaler provides clearer signals for variance preservation.

# Part 6: Choose the appropriate Scaler

Situation 1 (Normal distribution, no outliers): StandardScaler. Preserves the shape and variance profile cleanly.

Situation 2 (Extreme observations present): RobustScaler. Neutralizes outlier distortion using medians and IQRs.

Situation 3 (Constrained between 0 and 1): MinMaxScaler. Algebraically enforces hard minimum/maximum boundaries.

Situation 4 (Decision Tree): No Scaler Required. Decision trees branch by splitting features individually; monotonic transformations do not change the split points.

Situation 5 (K-Nearest Neighbours): StandardScaler / RobustScaler. Crucial because KNN uses Euclidean geometric distance metrics.

Situation 6 (K-Means clustering): StandardScaler. Equalizes scale parameters so all dimensions contribute equally to cluster centroids.

Situation 7 (Neural network): MinMaxScaler / StandardScaler. Stabilizes gradient descent optimization and prevents exploding weight states.

# Part 7: Pearson Correlation